<template>
  <div class="container-fluid">
    <div class="container">
      <div class="col-lg-8 col-12" style="padding: 0; margin: 0 auto;">
        <h1 class="page-title" style="margin-bottom: 25px;">Copyright Explained.</h1>
        <p class="gray-text">
          As we were developing Aslice, we quickly realized that copyrights,
          publishing and collections were fairly complicated topics that only a
          handful of people in our community truly had a solid grasp of. We too
          had a lot to learn, and that’s why we enlisted the help of Oliver Way,
          co-founder of the respected electronic music artist and label services
          organization EPM Music, to give us a crash course. What he taught us
          was not only incredibly helpful, but something that we knew would be
          relevant to all of our users, so we asked Oliver for permission to
          share his lessons publicly. This is by no means an exhaustive explanation—we 
          highly recommend further research when your needs go beyond the short 
          answers provided below—but it’s absolutely a great place to start. <br /><br />
          (The following content was provided to Aslice by Oliver Way c/o
          <span
            ><a href="https://www.epm-music.com/" target="_blank"
              >EPM Music</a
            ></span
          >, June 2021. Updated February 2024.)
        </p>
        <p class="section-title-purple">What Is Copyright?</p>
        <p class="gray-text">
          <ul>
            <li>Publishing royalties are for writers, composers and musicians and are collected by national societies, such as PRS for Music in the UK, GEMA in Germany, BMI & ASCAP in the US, SACEM in France, Buma Stemra in the Netherlands, etc.</li>
            <li>Sound recording royalties (a.k.a. neighboring rights) are collected by a different national society, such as PPL in the UK, Sound Exchange in the US, GVL in Germany, SENA in the Netherlands, etc.</li>
          </ul>
          You can join a society as a sound recording owner (i.e. record label), performer (i.e. artist) or both if you are an artist with your own label.
        </p>
        <p class="section-title-purple">What Is Publishing?</p>
        <p class="gray-text">
          Publishing refers to the royalties generated by a music composition (a.k.a. score), meaning the actual notes, frequencies and lyrics that make up a song.
<br /><br />
For example, on "Knights of the Jaguar," the publishing would stem from the notes played on the keys, the rhythm of the percussion and the various chord notes/patterns—in essence, everything that contributes to the structure of the track, as though it had been written down using music notation.
<br /><br />
The overall recording, which you might refer to as the track, is actually called something different. That is the sound recording or master, and it is different from the publishing.
        </p>
        <p class="section-title-purple">What Are (Publishing) Royalties?</p>
        <p class="gray-text">
          Royalties are payments made to a writer, composer or songwriter for use of their work, whether it’s a song they produced themselves or if it’s being used for someone else's song (this includes sampling).
          <br><br>
          In publishing, there are two sources of possible income:
          <ol>
            <li>Mechanicals, which stem from the sales of music (e.g. vinyl, CD, downloads, streams)</li>
            <li>Public performance, which stem from music being played on the radio, at public events or inside places such as retail spaces, hotels and restaurants; in short, they’re generated anytime music is played publicly by an entity with a license to do so.</li>
          </ol>
          When registering music for publishing, it is Important to include the following information:
          <br><br>
          <ol>
            <li>Track title
</li>
            <li>Track duration</li>
            <li>The real name(s) of the songwriter(s)
</li>
            <li>The ownership splits if more than one songwriter is involved (e.g. if a song has two songwriters, they can do an equal 50-50 split, or something else.)
</li>
            <li>If the songwriter(s) is/are a member of any collection society (e.g. PRS, BMI, ASCAP, GEMA, etc.)
</li>
            <li>If the songwriter(s) is/are a member of a collection society, their CAE/IPI number, which is their international member number. (The CAE/IPI number is important, especially in cases where multiple songwriters have the same name; without the number, the wrong songwriter could wind up being paid royalties.)</li>
          </ol>
        </p>
        <p class="section-title-purple">What Is A Publisher & What Are The Benefits They Provide?</p>
        <p class="gray-text">
          A publisher is someone who represents the publishing rights of songwriters/composers, making sure their music is properly registered into the society database(s) of the country (or countries) in which the publisher represents those rights. A publisher makes sure this data remains accurate, arranges updates when needed and ensures that royalties generated have been accounted for correctly.
          <br><br>
  
Although a songwriter can only join one collection society, a publisher can join many societies—technically they can join them all. This helps them to maintain the accuracy of song data (songwriters, shares, publishers, etc.) across multiple territories and also facilitates the faster collection of royalties.
<br><br>
Publishers also frequently facilitate collaborations between different songwriters that they represent, and some have creative departments that will look for other areas of possible revenue, such as music background companies (i.e. music being played in retail spaces, hotels, etc.) and sync licensing.
        </p>
        <p class="section-title-purple">What Are Master Rights?</p>
        <p class="gray-text">
          These are also referred to as sound recording rights and relate to the actual songs that have been recorded by artists (performers). They are usually owned by (or have been licensed to) a label, which will then release the songs.
<br><br>
Remember that a songwriter/composer of a song isn't necessarily the person who performs it on a record. In electronic music, the same person usually does both, but this is not the case in other genres of music. For instance, when it comes to pop music, the artists are usually the performers, but they often did not create or produce the music.
        </p>
        <p class="section-title-purple">What Are Neighboring Rights?</p>
        <p class="gray-text">
          Neighboring rights are performance royalties generated by sound recordings for artists (performers) and labels.
<br><br>
This is one area where the mainstream music industry and the dance music world can differ. Mainstream artists/performers are often not the writers/composers of their music, but in dance and electronic music, the artist and songwriter are usually the same person.
<br><br>
The music business, however, tends to cater to the mainstream.
<br><br>
For example, Madonna records and performs her own songs, but she isn’t necessarily the person who’s writing the music or the lyrics. On a song where she didn’t write the music or the lyrics, she doesn’t receive any publishing royalties; they are instead owned and collected by the actual composers/songwriters and their publishers.
<br><br>
In this instance Madonna would, however, collect the performer’s side of neighboring rights, while her label would collect the label side of the neighboring rights.
<br><br>
It needs to be pointed out that neighboring rights are generally not paid in the US, as the country did not join the Rome Convention Act in 1961, which determined compensation framework for performers when their music is broadcast on the radio and played in public spaces. 
        </p>
        <p class="section-title-purple">What Is A Neighboring Rights Society?</p>
        <p class="gray-text">
          A neighboring rights society is an organization responsible for the collection of master rights/sound recording performance royalties, and paying the royalties collected out to their performer/label members. 
<br><br>
It’s important to point out that neighboring rights are generally not paid in the US as they did not join the Rome Convention Act in 1961 to determine the compensation for performers for their music being broadcasted over radio and in public spaces. Because the US also does not pay performers from overseas, then overseas neighboring rights societies don't pay US performers/labels.
        </p>
        <p class="section-title-purple">What Is Public Performance Income?</p>
        <p class="gray-text">
          Public performance income is relatively self-explanatory, but it refers to royalties derived from the public performance of music (regardless of whether that music was played by a DJ, live act or streaming service). This includes music played on the radio and in public places that are paying the required license fee (e.g. clubs, bars, festivals, retail spaces, hotels, etc.)
 <br><br>
It’s important to stress that these royalties are only paid if music is played in a venue/location where the owners/organisers have paid relevant collection societies for a license. In practice, there are venues in which a DJ or live act may perform that are not official (i.e. they haven’t paid for a license to have music played at that location), which means public performance royalties will not be paid on plays which occur at those places.
<br><br>
The revenue from performance license fees paid by clubs, organisers and venue owners are divided up 50-50 between publishing rights and sound recordings (a.k.a. neighboring rights).
        </p>
        <p class="section-title-purple">What Is A Collection Society?</p>
        <p class="gray-text">
          Collection Societies are organizations responsible for the tracking, collection, and payment of earned royalties to copyright owners. This is a blanket term to refer to all organizations; individually, they are referred to as either performing rights organizations or collective management organizations.
        </p>
        <p class="section-title-purple">What Collection Society Should I Join?</p>
        <p class="gray-text">
          You can join any society you want, and although selecting the society based in your country of residence may seem like the obvious choice, it is not required. Just note that you can only join one society, so make sure to select the one that suits you best.
 <br><br>
Some general guidelines:<br>
If you are a writer/composer, you should join a publishing performing rights organisation (PRO). <br>
If you are an artist, you should join a neighboring rights society as a performer.<br>
If you are a label owner, you should join a neighboring rights society as a sound recording owner.
        </p>
        <p class="section-title-purple">What Is A Performing Rights Organization (PRO) & Which One Should I Join?</p>
        <p class="gray-text">
          A Performing Rights Organisation (PRO) is a national society responsible for the collection of performing rights, and paying the royalties collected to their songwriters/composers/publisher members.
  <br><br>
Remember, you can only join one society so pick it carefully.
 <br><br>
Songwriters/composers generally join their national PRO, but this is not essential; you can join any society around the world.
 <br><br>
For example, if you were making most of your sales and radio plays in the UK but were a US citizen, you could join PRS (the UK PRO).  The benefit of that being collecting direct from the national society from the country where the majority of your royalties are generated.
<br>
You can find a list of national PRO's from here:<br>
<a href="https://en.wikipedia.org/wiki/List_of_copyright_collection_societies" target="_blank">https://en.wikipedia.org/wiki/List_of_copyright_collection_societies</a>
        </p>
        <p class="section-title-purple">How Do Collection Societies Know Whose Music Is Publicly Performed?
</p>
        <p class="gray-text">
          In the current industry model, collection societies use the following three methods for determining what music might be publicly performed and who should be compensated with the money collected:
           <br><br>
           <ol>
             <li>MRT (Music Recognition Technology)<br>
               Some clubs and most festivals have a device installed to record sets.* These recordings are not for commercial use, and instead go directly to the company that installed the MRT, who audio fingerprint the sets in order to identify the tracks played. The lists of tracks generated by these companies are then sent to the relevant national societies (publishing and neighboring rights) for the territory in which the organization hosting the performances is based. (For example, for sets from Fabric in London, the lists of tracks are sent to PRS.
               <br><br>
               * Note: it is important to ask your booking agent to amend any clause in your contract regarding recording of your sets and ensure that it says no recording of your set is permitted for commercial reasons or upload to any public service/outlet. With this language, events and venues with MRT will still be allowed to use their devices to identify the music you play, ensuring that the license money they’ve paid gets back to the artists in your set (instead of mainstream pop stars—more on this below).</li>
               <br>
             <li>Set lists provided by DJs to services like Aslice, which you can then provide to your publisher for registration. (This can also be done by the DJ themselves if they are a member of a collection society.)
               <br><br>
               Many DJs don’t realize how important it is to register every single setlist with a collection society. In truth, it’s essential if you want any of the artists whose music you’re playing to receive the royalties they’re owed (which stem from the license fees paid by the promoter/venue who’ve contracted you for a gig). Without your setlists (or lists generated by MRT), that money instead falls into the "analogy" model of paying performers (see below), which results in the royalties going to the artists whose music is played most on the radio.</li>
             <br>
             <li>Music "analogy"<br>
If MRT isn’t used and the DJ doesn’t submit their setlist, the royalties are instead often diverted toward the most-played songs on the radio and divided up between those artists. Under this model, the artists you actually support will receive nothing—unless you’re playing Ed Sheeran and Arianna Grande in your sets.</li>
           </ol>
        </p>
        <p class="section-title-purple">Do I Need To Have A Publisher, A Collection Society & PRO?</p>
        <p class="gray-text">
          No, you don't have to do any of these things if you don't want to make any copyright royalties from your music.  The royalties earned from your music will then just be distributed amongst the members of the societies.
          <br><br>
          We at EPM Music and Aslice believe the answer should be, “yes, you do need to join,” so you can collect the copyright royalties that are yours.
          <br><br>
          <a href="mailto:publishing@epm-music.com" class="section-title-purple">If you are a writer/composer of music or a label owner, and you’re interested in representation for publishing and/or neighboring rights, please contact Oliver from EPM Music at publishing@epm-music.com</a>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Copyright",
  metaInfo: {
    title: "Copyright Explained",
    meta: []
  },
};
</script>

<style scoped>
.container-fluid {
  padding: 3.5px 21.5px;
  padding-top: 150px;
  padding-bottom: 210px;
  min-height: calc(100vh - 365px);
  background: #e5e5e5;
}
</style>
